disabled_rules:
 - force_cast
 - force_try
 - trailing_whitespace
 - line_length

included:
    - ../Sources

excluded:
 - Pods

type_name:
 excluded:
  - KOVisualEffectDimmingPresentationController

identifier_name: 
 excluded:
  - id