# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KOControlsExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KOControlsExample
  pod 'SwiftLint', '~> 0.30'
  pod 'IQKeyboardManagerSwift', '~> 6.1'

end
